config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts
  resources :comments
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  root "root#home"
 
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments
    resources :likes
  end

end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post_id, presence: true
  validates :user_id, presence: true
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id}
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  

  private
    # Проводит валидацию размера загруженного изображения.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "должно быть меньше, чем 5MB")
    end
  end

    

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  validates :name, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }



# Возвращает ленту сообщений пользователя.
def feed
  feed_authors = following.ids << id
  Post.where(user_id: feed_authors)
end

# подписаться на пользователя.
def follow(other_user)
  active_relationships.create(followed_id: other_user.id)
end

# отписаться от пользователя.
def unfollow(other_user)
  status = active_relationships.find_by(followed_id: other_user.id)
  if status.present?
    status.destroy
  end
end

# Возвращает true, если текущий пользователь подписан на другого пользователя.
def following?(other_user)
 following.include?(other_user)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
  @post = Post.find(params[:post_id])
  params = comment_params.merge({ user: current_user })
  @comment = @post.comments.build(params)
    if @comment.save
      redirect_to request.referrer || root_url
    else
      flash[:alert] = "Error"
    end
end
    
def destroy
  @comment = Comment.find(params[:id])
  @comment.destroy
  redirect_to request.referrer || root_url
end

private

def comment_params
  params.require(:comment).permit(:body)
end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

def create
  @like = current_user.likes.create(like_params)
    if @like.save
    redirect_to request.referrer || root_url
    else
      flash.now[:alert] = "Error"
    end
end
        
def destroy
  @like = Like.find(params[:id])
  @like.destroy
  redirect_to request.referrer || root_url
end

private

def like_params
  params.require(:like).permit(:post_id)
end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user,   only: :destroy

  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
      if @post.update(post_params)
        flash[:success] = "Profile updated"
        redirect_to root_url
      else
        render 'edit'
      end
  end

  def create
    @post = current_user.posts.build(post_params)
      if @post.save
        flash[:success] = "publication created!"
        redirect_to root_url
      else
        @feed_items = []
        render 'root/home'
      end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Публикация удалена"
    redirect_to request.referrer || root_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :picture)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end
      
  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  skip_before_action :authenticate_user!
    
  def home
    if user_signed_in?
      @post  = current_user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @comments = Comment.where(post_id: params[:post_id])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Welcome!"
        redirect_to @user
      else
        flash.now[:alert] = "Error"
        render 'new'
      end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    params = build_params(user_params)
      if @user.update(params)
        flash[:success] = "Profile updated"
        redirect_to user_url(@user)
      else
        render 'edit'
      end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def build_params(user_params)
    user_params[:password] = user_params[:password].presence
    user_params[:password_confirmation] = user_params[:password_confirmation].presence
    user_params.compact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
      end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Project</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
 
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li><%= link_to "Profile", current_user  %></li>
        <li><%= link_to "Log out", destroy_user_session_path, data: {"turbo-method": :delete} %></li>
    </li>
      <% else %>
        <li><%= link_to "Зарегистрироваться",  new_user_registration_path %></li>
        <li><%= link_to "Зайти",  user_session_path %></li>
      <% end %>
  </ul>

  <%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
<%@feed_items = current_user.feed.paginate(page: params[:page])%>
<% if @feed_items.any? %>
   
   </br><span class="user">
    <%= link_to post.user.email, post.user %></span>
   
  <span class="post">
    <%= post.content %>
    <%= image_tag post.picture.url if post.picture? %>
  </span>

  <span class="timestamp"> 
        Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
  <span class="like"> 
    <i class="bi bi-suit-heart-fill"></i>
    <%= post.likes.count %> Likes</span>

  <div class="likes"> <p>
    <% like = current_user.likes.find_by(post: post) %>
  <% if like.nil? %>
    <%= button_to "Like post", likes_path(post), params: { like: { post_id: post.id }}, method: :post %>
  <% else %>
    <%= button_to "DisLike post", like_path(like), method: :delete %>
  <% end %>
     <% if current_user?(post.user) %>
        <%= link_to "delete post", post_path(post), data: {"turbo-method": :delete} %>
        <i class="bi bi-signpost-2" style=color:blue></i>
        <%= link_to "edit post", edit_post_path(post) %>
      <% end %>
    

   </p> </div>

  <p class="exampleTitle">Комментарии</p>
  <p class="example">
  <% post.comments.each do |comment| %>
    <span>
      <%= link_to comment.user.email, comment.user, style: "color: black" %>:
      <%= comment.body %> </br>
        <% if current_user?(post.user) || current_user?(comment.user)%>
          <%= link_to "delete comment", comment_path(comment), data: {"turbo-method": :delete} %>
        </br> <% end %>
      <% end %>
  </p>

  <%= form_with(model: [ post, Comment.new ]) do |form| %>
  <div class = "commenting">
    <%= form.text_area :body, placeholder: "Your review...", required: true %>
    <%= form.submit "comment", class: "btn btn-primary"%>
  </div>
  
<% end %>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-md-4">
    </div>  

  <div class="col-xs-6 col-md-4">
    <aside>
    <%= form_for(@post, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="center">
    <%= f.text_area :content %>
    </div>
    
    <span class="picture">
    <%= image_tag @post.picture.url if @post.picture? %>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    <p>
   <%= f.submit "Редактировать", class: "btn btn-primary" %> 
    </p>
    </aside>
    <% end %>

    <script type="text/javascript">
    $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
      alert('Максимальный размер файла — 5 МБ. Пожалуйста, выберите файл меньшего размера.');
      }
      });
    </script>

  </div>
  <div class="col-xs-6 col-md-4">
  </div>  
  </div>
</div>
  

app/views/root/home.html.erb
<% if user_signed_in? %>
  <div class="container">
  <div class="row">
  <div class="col-xs-6 col-md-4">
    
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>

    <section class="stats">
      <%= render 'shared/stats' %>
    </section>

    <p> <section class="publication_form">
    <%= render 'shared/publication_form' %></section> </p>

  </div>  

    <div class="col-xs-12 col-md-8">
      <h3>Лента публикаций</h3>
      <%= render 'shared/feed' %>
      
    </div>
  </div>
  </div>
<% else %>
    <div class="center jumbotron">
    <h1>Welcome to the InstaProject</h1>
    <h2> This is the home page for the InstaProject </h2>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %> </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="publications">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_publication_form.html.erb
<aside>
<%= form_for(@post, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="center">
  <%= f.text_area :content, placeholder: "My new post..." %>
  </div>
  
  <span class="picture">
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <p>
  <%= f.submit "Post", class: "btn btn-primary" %> 
  </p>
</aside>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Максимальный размер файла — 5 МБ. Пожалуйста, выберите файл меньшего размера.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    подписан
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    подписчики
  </a>
</div>

app/views/shared/_user_info.html.erb
<p><span class="profile_name"><%= current_user.name %></span></p>
<p><span class="profile"><%= link_to "Мой профиль", current_user %></span></p>
<p><span><%= pluralize(current_user.posts.count, "publication") %></span></p>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Подписаться", class: "btn btn-primary" %>
<% end %>
  

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Отписаться", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

  
  <div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= form_with(model: current_user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>    
  </div>
  </div>

 

app/views/users/index.html.erb
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up/Регистрация</h1>
  
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
  <%= render 'follow_form' if !current_user.nil? %>
    <% if @user.posts.any? %>
      <h3>Публикация <%= @user.posts.count %> </h3>
      <ol class="publications">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span class="profile"><%= link_to "Мой профиль", @user %></span>
      <span><b>Публикации:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
     </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="profile">
      <% @users.each do |user| %>
        <%= link_to user.name, user %> </br>
        <% end %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>